#!/bin/bash

git add -A
echo "Enter in commit message: "
read commitMessage
git commit -m "$commitMessage"
echo "Which branch do you want to push to? (default master)"
read branch
git push origin $branch
