#!/bin/bash

git add-A
echo "Enter in commit message:"
read commitMessage
git commit - m "$commitMessage"
echo "Which branch do you want to push to?"
	if [ $branch == "" ]; then
	push master
	fi
read branch
git push origin $master

